export enum AuthError {
  USER_NOT_FOUND = 'USER NOT FOUND',
  WRONG_PASSWORD = 'WRONG PASSWORD',
  ACCOUNT_ALREADY_EXISTS = 'ACCOUNT ALREADY EXISTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
}
